drop_cols:
  - 'EmployeeCount'
  - 'EmployeeNumber'
  - 'Over18'
  - 'StandardHours'

need_dummy_cols:
  - 'BusinessTravel'
  - 'Department'
  - 'Education'
  - 'EducationField'
  - 'EnvironmentSatisfaction'
  - 'Gender'
  - 'JobInvolvement'
  - 'JobLevel'
  - 'JobRole'
  - 'MaritalStatus'

test_size: 0.3
random_state: 1